AWSTemplateFormatVersion: 2010-09-09
Description: Create ec2 instance with CloudFormation

Parameters:
  AmiID:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: "The ID of the AMI."
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
  InstanceType:
    Type: String
    Description: Instance type need to provide like t2.micro, t2.medium etc..,
  KeyPairName:
    Type: String
    Description: Provide Key pair name for instance
  TagName:
    Type: String
    Description: Name of Instance

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiID # ImageID valid only in us-east-1 region
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyPairName
      SecurityGroups: [!Ref InstanceSecurityGroup]
      Tags:
        - Key: Name
          Value: !Ref TagName
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

Outputs:
  PublicIp:
    Description: Instance public ip value
    Value: !GetAtt [Ec2Instance, PublicIp]